#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LexPOC.Resource", IsApplication=true)]

namespace LexPOC
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::LexPOC.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::LexPOC.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::LexPOC.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::LexPOC.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int green = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int light_grey = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int red = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int response_background = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int response_foreground = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int buttonStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int clear = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int start = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int stop = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int chat = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int clear = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int parentLayout = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int recordText = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int scroll = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int start = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
